### ISSUE TITLE
[fix] 스마트캠퍼스 크롤링 로직 lambda_handler와 연결

### ISSUE THREAD

**Issue by k0000k** [DaITssu/daitssu-crawl#31]
스마트캠퍼스 크롤링 로직은 현재 lambda_handler와 연결되어 있지 않은 상태입니다. 람다에서 호출할 수 있게 제가 주석으로 처리해둔 부분의 코드를 채워주세요.

**Comment by NokboongI** [comment]
제 코드가 SmartCampus라는 클래스 안에 각 역할을 하는 여러 메소드들로 구성이 되어있는데, if문을 사용하여 result에 넣어줄 값을 조절해줘야 할까요?
